### ISSUE TITLE
Rework validate method

### ISSUE THREAD

**Issue by Navel-IT** [Navel-IT/navel-base#15]
Rework validate method:
- remove `Data::Validate::Struct` (far too slow to load: 10.000 objects took ~ 60s while in PP it's took less than 1s) and use PP (without regex).

**Comment by Navel-IT** [comment]
https://metacpan.org/pod/JSON::Validator

**Comment by le-garff-yoann** [comment]
a9a825aaa4f2ebcf4231f29f3385968255ade80c
